[server]
name = "public"
addr = ":23200"
env = "test"


[mysql]
name = "public"
master = "root:@tcp(127.0.0.1:3306)/public?charset=utf8mb4&parseTime=true&loc=Local"
slave = "root:@tcp(127.0.0.1:3306)/public?charset=utf8mb4&parseTime=true&loc=Local"


[redis]
name = "public"
addr = "127.0.0.1:6379"
password = ""
db = 0